// frontend/src/components/settings/UserManagement.tsx
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { authApi, type User } from '@/api/auth'
import { DEFAULT_PAGE_SIZE } from '@/constants/pagination'
import { useConfirm } from '@/composables/useConfirm'
import { useToastStore } from '@/composables/useToast'

interface UserForm {
  department: string
  email: string
  name: string
  password: string
  phone: string
  position: string
  role: 'admin' | 'user'
  status: number
  username: string
}

const emptyForm: UserForm = {
  department: '',
  email: '',
  name: '',
  password: '',
  phone: '',
  position: '',
  role: 'user',
  status: 1,
  username: '',
}

const getVisiblePages = (currentPage: number, totalPages: number) => {
  if (totalPages <= 7) return Array.from({ length: totalPages }, (_, index) => index + 1)

  const pages: Array<number | string> = [1]
  const delta = 2
  let start = currentPage - delta
  let end = currentPage + delta

  if (start <= 2) {
    start = 2
    end = Math.min(6, totalPages - 1)
  } else if (end >= totalPages - 1) {
    end = totalPages - 1
    start = Math.max(totalPages - 5, 2)
  }

  if (start > 2) pages.push('...')
  for (let page = start; page <= end; page += 1) pages.push(page)
  if (end < totalPages - 1) pages.push('...')
  if (totalPages > 1) pages.push(totalPages)

  return pages
}

export default function UserManagement() {
  const { confirm } = useConfirm()
  const toastError = useToastStore((state) => state.error)
  const toastSuccess = useToastStore((state) => state.success)
  const [users, setUsers] = useState<User[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [searchKeyword, setSearchKeyword] = useState('')
  const [currentPage, setCurrentPage] = useState(1)
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE)
  const [showModal, setShowModal] = useState(false)
  const [editingUser, setEditingUser] = useState<User | null>(null)
  const [form, setForm] = useState<UserForm>(emptyForm)
  const [resetPasswordUser, setResetPasswordUser] = useState<User | null>(null)
  const [newPassword, setNewPassword] = useState('')

  const adminCount = users.filter((user) => user.role === 'admin').length
  const userCount = users.filter((user) => user.role !== 'admin').length
  const totalPages = Math.ceil(total / pageSize)
  const visiblePages = useMemo(() => getVisiblePages(currentPage, totalPages), [currentPage, totalPages])

  const paginationInfo = useMemo(() => {
    if (total === 0) return '暂无数据'
    const start = (currentPage - 1) * pageSize + 1
    const end = Math.min(currentPage * pageSize, total)
    return `显示 ${start}-${end} 条，共 ${total} 条`
  }, [currentPage, pageSize, total])

  const loadUsers = useCallback(async () => {
    setLoading(true)
    try {
      const response = await authApi.getUsers({
        keyword: searchKeyword || undefined,
        page: currentPage,
        page_size: pageSize,
      })
      setUsers(response.data.data.list)
      setTotal(response.data.data.total)
    } catch {
      toastError('获取用户失败')
    } finally {
      setLoading(false)
    }
  }, [currentPage, pageSize, searchKeyword, toastError])

  useEffect(() => {
    const timer = window.setTimeout(loadUsers, 0)
    return () => window.clearTimeout(timer)
  }, [loadUsers])

  const openAddModal = () => {
    setEditingUser(null)
    setForm(emptyForm)
    setShowModal(true)
  }

  const openEditModal = (user: User) => {
    setEditingUser(user)
    setForm({
      department: user.department || '',
      email: user.email || '',
      name: user.name || '',
      password: '',
      phone: user.phone || '',
      position: user.position || '',
      role: user.role === 'admin' ? 'admin' : 'user',
      status: user.status,
      username: user.username,
    })
    setShowModal(true)
  }

  const handleSearch = () => {
    setCurrentPage(1)
    setSearchKeyword(keyword)
  }

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    try {
      if (editingUser) {
        await authApi.updateUser(editingUser.id, {
          department: form.department,
          email: form.email,
          name: form.name,
          phone: form.phone,
          position: form.position,
          role: form.role,
          status: form.status,
        })
        toastSuccess('用户已更新')
      } else {
        await authApi.createUser({
          email: form.email,
          name: form.name,
          password: form.password,
          phone: form.phone,
          role: form.role,
          username: form.username,
        })
        toastSuccess('用户已创建')
      }

      setShowModal(false)
      await loadUsers()
    } catch {
      toastError(editingUser ? '更新用户失败' : '创建用户失败')
    }
  }

  const handleDelete = async (user: User) => {
    const confirmed = await confirm(`确定要删除用户「${user.name || user.username}」吗？此操作不可恢复。`)
    if (!confirmed) return

    try {
      await authApi.deleteUser(user.id)
      toastSuccess('用户已删除')
      await loadUsers()
    } catch {
      toastError('删除用户失败')
    }
  }

  const handleResetPassword = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!resetPasswordUser) return

    try {
      await authApi.resetPassword(resetPasswordUser.id, newPassword)
      toastSuccess('密码已重置')
      setResetPasswordUser(null)
      setNewPassword('')
    } catch {
      toastError('重置密码失败')
    }
  }

  return (
    <div className="user-management">
      <div className="dev-header">
        <div className="dev-header-content">
          <div className="dev-title-section">
            <div className="dev-icon-wrapper">
              <i className="ri-team-line" />
            </div>
            <div className="dev-title-info">
              <h2 className="dev-title">用户管理</h2>
              <p className="dev-subtitle">管理系统用户账户和权限设置</p>
            </div>
          </div>
          <button className="dev-create-btn" onClick={openAddModal} type="button">
            <i className="ri-add-line" />
            <span>新增用户</span>
          </button>
        </div>

        <div className="dev-stats">
          <div className="dev-stat-card">
            <div className="dev-stat-icon total">
              <i className="ri-group-line" />
            </div>
            <div className="dev-stat-info">
              <span className="dev-stat-value">{total}</span>
              <span className="dev-stat-label">总用户</span>
            </div>
          </div>
          <div className="dev-stat-card">
            <div className="dev-stat-icon admin">
              <i className="ri-shield-user-line" />
            </div>
            <div className="dev-stat-info">
              <span className="dev-stat-value">{adminCount}</span>
              <span className="dev-stat-label">管理员</span>
            </div>
          </div>
          <div className="dev-stat-card">
            <div className="dev-stat-icon user">
              <i className="ri-user-line" />
            </div>
            <div className="dev-stat-info">
              <span className="dev-stat-value">{userCount}</span>
              <span className="dev-stat-label">普通用户</span>
            </div>
          </div>
        </div>
      </div>

      <div className="dev-content">
        <div className="search-input-wrapper">
          <i className="ri-search-line search-icon" />
          <input
            autoCapitalize="off"
            autoComplete="off"
            autoCorrect="off"
            className="search-input"
            onChange={(event) => setKeyword(event.target.value)}
            onKeyUp={(event) => {
              if (event.key === 'Enter') handleSearch()
            }}
            placeholder="搜索用户名或姓名..."
            spellCheck={false}
            type="text"
            value={keyword}
          />
        </div>

        {loading ? (
          <div className="dev-loading">
            <div className="dev-loading-spinner">
              <i className="ri-loader-4-line animate-spin" />
            </div>
            <span>正在加载用户列表...</span>
          </div>
        ) : users.length === 0 ? (
          <div className="dev-empty">
            <div className="dev-empty-icon">
              <i className="ri-user-unfollow-line" />
            </div>
            <h3 className="dev-empty-title">暂无用户</h3>
            <p className="dev-empty-desc">点击右上角按钮添加新用户</p>
          </div>
        ) : (
          <div className="user-list">
            {users.map((user) => (
              <div className="user-card" key={user.id}>
                <div className={`user-avatar ${user.role === 'admin' ? 'avatar-admin' : 'avatar-user'}`}>
                  <i className={user.role === 'admin' ? 'ri-shield-user-fill' : 'ri-user-fill'} />
                </div>

                <div className="user-info">
                  <div className="user-name-row">
                    <span className="user-name">{user.name || user.username}</span>
                    <span className={`user-role-badge ${user.role === 'admin' ? 'role-admin' : 'role-user'}`}>
                      {user.role === 'admin' ? '管理员' : '普通用户'}
                    </span>
                    <span className={`user-status ${user.status === 1 ? 'status-active' : 'status-disabled'}`}>
                      <span className="status-dot" />
                      {user.status === 1 ? '正常' : '禁用'}
                    </span>
                  </div>
                  <div className="user-meta">
                    <span className="meta-item">
                      <i className="ri-at-line" /> {user.username}
                    </span>
                    {user.department ? (
                      <span className="meta-item">
                        <i className="ri-building-line" /> {user.department}
                      </span>
                    ) : null}
                    {user.position ? (
                      <span className="meta-item">
                        <i className="ri-briefcase-line" /> {user.position}
                      </span>
                    ) : null}
                  </div>
                  {user.email || user.phone ? (
                    <div className="user-contact">
                      {user.email ? (
                        <span className="contact-item">
                          <i className="ri-mail-line" /> {user.email}
                        </span>
                      ) : null}
                      {user.phone ? (
                        <span className="contact-item">
                          <i className="ri-phone-line" /> {user.phone}
                        </span>
                      ) : null}
                    </div>
                  ) : null}
                </div>

                <div className="user-actions">
                  <button className="action-btn edit" onClick={() => openEditModal(user)} title="编辑" type="button">
                    <i className="ri-edit-line" />
                  </button>
                  <button
                    className="action-btn key"
                    onClick={() => {
                      setResetPasswordUser(user)
                      setNewPassword('')
                    }}
                    title="重置密码"
                    type="button"
                  >
                    <i className="ri-key-line" />
                  </button>
                  <button
                    className="action-btn delete"
                    onClick={() => void handleDelete(user)}
                    title="删除"
                    type="button"
                  >
                    <i className="ri-delete-bin-line" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {users.length > 0 ? (
          <div className="user-pagination">
            <div className="pagination-inner">
              <span className="pagination-info">{paginationInfo}</span>

              <div className="pagination-controls">
                <button
                  className="page-btn"
                  disabled={currentPage === 1}
                  onClick={() => setCurrentPage((page) => Math.max(1, page - 1))}
                  type="button"
                >
                  <i className="ri-arrow-left-s-line" />
                </button>

                <div className="page-numbers">
                  {visiblePages.map((page, index) => (
                    <button
                      className={`page-number ${currentPage === page ? 'active' : ''} ${
                        page === '...' ? 'cursor-default' : ''
                      }`}
                      disabled={currentPage === page || page === '...'}
                      key={`${page}-${index}`}
                      onClick={() => typeof page === 'number' && setCurrentPage(page)}
                      type="button"
                    >
                      {page}
                    </button>
                  ))}
                </div>

                <button
                  className="page-btn"
                  disabled={currentPage === totalPages}
                  onClick={() => setCurrentPage((page) => Math.min(totalPages, page + 1))}
                  type="button"
                >
                  <i className="ri-arrow-right-s-line" />
                </button>
              </div>

              <div className="page-size">
                <select
                  className="page-select"
                  onChange={(event) => {
                    setPageSize(Number(event.target.value))
                    setCurrentPage(1)
                  }}
                  value={pageSize}
                >
                  <option value={5}>5条/页</option>
                  <option value={10}>10条/页</option>
                </select>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      {showModal ? (
        <div className="modal-overlay open" onClick={() => setShowModal(false)} role="presentation">
          <div className="modal open" onClick={(event) => event.stopPropagation()} style={{ maxHeight: '90vh', width: 560 }}>
            <div
              className="modal-header"
              style={{
                borderBottom: '1px solid var(--separator-color)',
                marginBottom: 24,
                paddingBottom: 16,
              }}
            >
              <h3 className="modal-title">{editingUser ? '编辑用户' : '新增用户'}</h3>
              <button className="modal-close" onClick={() => setShowModal(false)} type="button">
                <i className="ri-close-line" />
              </button>
            </div>
            <form className="modal-body grid gap-4" onSubmit={handleSubmit}>
              <div className="grid grid-cols-2 gap-4">
                <div className="form-group">
                  <label className="form-label">
                    用户名 <span className="text-danger">*</span>
                  </label>
                  <input
                    className="form-input"
                    disabled={Boolean(editingUser)}
                    onChange={(event) => setForm((current) => ({ ...current, username: event.target.value }))}
                    required
                    value={form.username}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">
                    姓名 <span className="text-danger">*</span>
                  </label>
                  <input
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))}
                    required
                    value={form.name}
                  />
                </div>
              </div>

              {!editingUser ? (
                <div className="form-group">
                  <label className="form-label">
                    初始密码 <span className="text-danger">*</span>
                  </label>
                  <input
                    autoComplete="new-password"
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, password: event.target.value }))}
                    required
                    type="password"
                    value={form.password}
                  />
                </div>
              ) : null}

              <div className="grid grid-cols-2 gap-4">
                <div className="form-group">
                  <label className="form-label">角色</label>
                  <div className="input-wrapper">
                    <select
                      className="form-select"
                      onChange={(event) =>
                        setForm((current) => ({ ...current, role: event.target.value as 'admin' | 'user' }))
                      }
                      value={form.role}
                    >
                      <option value="user">普通用户</option>
                      <option value="admin">管理员</option>
                    </select>
                    <i className="ri-arrow-down-s-line select-arrow" />
                  </div>
                </div>
                <div className="form-group">
                  <label className="form-label">状态</label>
                  <div className="input-wrapper">
                    <select
                      className="form-select"
                      onChange={(event) => setForm((current) => ({ ...current, status: Number(event.target.value) }))}
                      value={form.status}
                    >
                      <option value={1}>正常</option>
                      <option value={0}>禁用</option>
                    </select>
                    <i className="ri-arrow-down-s-line select-arrow" />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="form-group">
                  <label className="form-label">邮箱</label>
                  <input
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))}
                    type="email"
                    value={form.email}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">手机</label>
                  <input
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, phone: event.target.value }))}
                    value={form.phone}
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="form-group">
                  <label className="form-label">部门</label>
                  <input
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, department: event.target.value }))}
                    value={form.department}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">职位</label>
                  <input
                    className="form-input"
                    onChange={(event) => setForm((current) => ({ ...current, position: event.target.value }))}
                    value={form.position}
                  />
                </div>
              </div>

              <div className="modal-footer">
                <button className="btn btn-ghost" onClick={() => setShowModal(false)} type="button">
                  取消
                </button>
                <button className="btn btn-primary" type="submit">
                  保存
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}

      {resetPasswordUser ? (
        <div className="modal-overlay open" onClick={() => setResetPasswordUser(null)} role="presentation">
          <div className="modal open" onClick={(event) => event.stopPropagation()} style={{ width: 420 }}>
            <div className="modal-header">
              <h3 className="modal-title">重置密码 - {resetPasswordUser.username}</h3>
              <button className="modal-close" onClick={() => setResetPasswordUser(null)} type="button">
                <i className="ri-close-line" />
              </button>
            </div>
            <form className="modal-body" onSubmit={handleResetPassword}>
              <div className="form-group">
                <label className="form-label">
                  新密码 <span className="text-danger">*</span>
                </label>
                <input
                  autoComplete="new-password"
                  className="form-input"
                  onChange={(event) => setNewPassword(event.target.value)}
                  required
                  type="password"
                  value={newPassword}
                />
              </div>
              <div className="modal-footer">
                <button className="btn btn-ghost" onClick={() => setResetPasswordUser(null)} type="button">
                  取消
                </button>
                <button className="btn btn-primary" type="submit">
                  确认重置
                </button>
              </div>
            </form>
          </div>
        </div>
      ) : null}
    </div>
  )
}

// frontend/src/views/settings/UserManagement.vue
<script setup lang="ts">
import { ref, onMounted, reactive, computed } from 'vue'
import { authApi, type User, type CreateUserRequest, type UpdateUserRequest } from '@/api/auth'
import { useToast } from '@/composables/useToast'
import { useConfirm } from '@/composables/useConfirm'

const toast = useToast()
const { confirm } = useConfirm()

// State
const users = ref<User[]>([])
const total = ref(0)
const loading = ref(false)
const currentPage = ref(1)
const pageSize = ref(5)
const keyword = ref('')

// Modal State
const showModal = ref(false)
const isEditing = ref(false)
const modalLoading = ref(false)
const showResetPwdModal = ref(false)

const form = reactive({
  id: 0,
  username: '',
  name: '',
  email: '',
  phone: '',
  role: 'user',
  position: '',
  department: '',
  status: 1,
  password: '' // Only for create
})

const resetPwdForm = reactive({
  id: 0,
  username: '',
  password: ''
})

// Fetch Data
const fetchUsers = async () => {
  loading.value = true
  try {
    const res = await authApi.getUsers({
      page: currentPage.value,
      page_size: pageSize.value,
      keyword: keyword.value,
      _t: Date.now() // Force refresh
    })
    if (res.data.code === 0) {
      users.value = res.data.data.list
      total.value = res.data.data.total
    }
  } catch (error) {
    console.error(error)
    toast.error('获取用户列表失败')
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  currentPage.value = 1
  fetchUsers()
}

// Pagination Logic
const totalPages = computed(() => Math.ceil(total.value / pageSize.value))

const paginationInfo = computed(() => {
  if (total.value === 0) return '暂无数据'
  const start = (currentPage.value - 1) * pageSize.value + 1
  const end = Math.min(currentPage.value * pageSize.value, total.value)
  return `显示 ${start}-${end} 条，共 ${total.value} 条`
})

const prevPage = () => {
  if (currentPage.value > 1) {
    currentPage.value--
    fetchUsers()
  }
}

const nextPage = () => {
  if (currentPage.value < totalPages.value) {
    currentPage.value++
    fetchUsers()
  }
}

const goToPage = (page: number) => {
  if (page !== currentPage.value) {
    currentPage.value = page
    fetchUsers()
  }
}

// Actions
const openAddModal = () => {
  isEditing.value = false
  Object.assign(form, {
    id: 0,
    username: '',
    name: '',
    email: '',
    phone: '',
    role: 'user',
    position: '',
    department: '',
    status: 1,
    password: ''
  })
  showModal.value = true
}

const openEditModal = (user: User) => {
  isEditing.value = true
  Object.assign(form, {
    id: user.id,
    username: user.username,
    name: user.name,
    email: user.email,
    phone: user.phone,
    role: user.role,
    position: user.position,
    department: user.department,
    status: user.status,
    password: ''
  })
  showModal.value = true
}

const handleSubmit = async () => {
  if (!form.username || !form.name) {
    toast.warning('请填写必填项(用户名、姓名)')
    return
  }
  if (!isEditing.value && !form.password) {
      toast.warning('创建用户必须设置初始密码')
      return
  }
  
  modalLoading.value = true
  try {
    if (isEditing.value) {
      const updateData: UpdateUserRequest = {
        name: form.name,
        email: form.email,
        phone: form.phone,
        department: form.department,
        position: form.position,
        role: form.role,
        status: form.status
      }
      const res = await authApi.updateUser(form.id, updateData)
      if (res.data.code === 0) {
        toast.success('更新成功')
        showModal.value = false
        fetchUsers()
      } else {
        toast.error(res.data.message || '更新失败')
      }
    } else {
      const createData: CreateUserRequest = {
        username: form.username,
        name: form.name,
        email: form.email,
        phone: form.phone,
        password: form.password,
        role: form.role as 'admin'|'user'
      }
      const res = await authApi.createUser(createData)
      if (res.data.code === 0) {
        toast.success('创建成功')
        showModal.value = false
        
        // Reset state to ensure new user is visible
        keyword.value = '' 
        currentPage.value = 1
        
        // Wait a bit to ensure backend consistency and then fetch
        setTimeout(() => {
          fetchUsers()
        }, 300)
      } else {
        toast.error(res.data.message || '创建失败')
      }
    }
  } catch (error) {
    const msg = (error as Error).message || '操作失败'
    toast.error(msg)
  } finally {
    modalLoading.value = false
  }
}

const handleDelete = async (user: User) => {
  if (await confirm(`确定要删除用户 "${user.name}" 吗？此操作不可恢复。`)) {
    try {
      const res = await authApi.deleteUser(user.id)
      if (res.data.code === 0) {
        toast.success('删除成功')
        fetchUsers()
      } else {
        toast.error(res.data.message || '删除失败')
      }
    } catch {
      toast.error('删除失败')
    }
  }
}

// Reset Password
const openResetPwdModal = (user: User) => {
  resetPwdForm.id = user.id
  resetPwdForm.username = user.username
  resetPwdForm.password = ''
  showResetPwdModal.value = true
}

const handleResetPwd = async () => {
  if (!resetPwdForm.password || resetPwdForm.password.length < 6) {
    toast.warning('密码长度至少6位')
    return
  }
  
  try {
    const res = await authApi.resetPassword(resetPwdForm.id, resetPwdForm.password)
    if (res.data.code === 0) {
      toast.success('密码重置成功')
      showResetPwdModal.value = false
    } else {
      toast.error(res.data.message || '重置失败')
    }
  } catch {
    toast.error('重置失败')
  }
}

onMounted(() => {
  fetchUsers()
})
</script>

<template>
  <div class="user-management flex flex-col">
    <!-- Header/Toolbar -->
    <div class="glass-card-header border-b p-md flex justify-between items-center" style="border-bottom-color: var(--separator-color);">
      <h3 class="glass-card-title">用户管理</h3>

      <div class="flex gap-sm items-center">
        <!-- Search Input -->
        <div class="search-input-wrapper">
          <i class="ri-search-line search-icon"></i>
          <input 
            v-model="keyword" 
            type="text" 
            placeholder="搜索用户..." 
            class="search-input"
            spellcheck="false"
            autocomplete="off"
            autocorrect="off"
            autocapitalize="off"
            @keyup.enter="handleSearch"
          />
        </div>
        
        <button class="btn btn-primary btn-sm" @click="openAddModal">
          <i class="ri-add-line"></i> <span class="btn-text">新增用户</span>
        </button>
      </div>
    </div>

    <!-- Table Container (No GlassCard) -->
    <div class="flex flex-col overflow-hidden">
      <div class="overflow-auto" style="height: 420px;">
        <table class="data-table w-full">
          <thead>
            <tr>
              <th width="80" class="pl-md">ID</th>
              <th>用户名</th>
              <th>姓名</th>
              <th>角色</th>
              <th>职位/部门</th>
              <th>联系方式</th>
              <th>状态</th>
              <th class="col-fixed-right text-right pr-md">操作</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="loading">
              <td colspan="8" class="text-center py-8 text-secondary">加载中...</td>
            </tr>
            <tr v-else-if="users.length === 0">
              <td colspan="8">
                 <div class="flex flex-col items-center justify-center py-xl text-secondary">
                  <i class="ri-user-unfollow-line text-4xl mb-sm opacity-50"></i>
                  <p>暂无用户数据</p>
                </div>
              </td>
            </tr>
            <tr 
              v-for="user in users" 
              :key="user.id"
              class="user-row hover:bg-white/5 transition-colors"
            >
              <td class="pl-md">{{ user.id }}</td>
              <td class="font-medium">{{ user.username }}</td>
              <td>{{ user.name }}</td>
              <td>
                <span class="badge" :class="user.role === 'admin' ? 'badge-primary' : 'badge-secondary'">
                  {{ user.role === 'admin' ? '管理员' : '普通用户' }}
                </span>
              </td>
              <td>
                <div class="text-sm">{{ user.position || '-' }}</div>
                <div class="text-xs text-secondary">{{ user.department || '-' }}</div>
              </td>
              <td>
                <div class="text-sm">{{ user.email || '-' }}</div>
                <div class="text-xs text-secondary">{{ user.phone || '-' }}</div>
              </td>
              <td>
                <span class="status-dot" :class="user.status === 1 ? 'bg-success' : 'bg-danger'"></span>
                {{ user.status === 1 ? '正常' : '禁用' }}
              </td>
              <td class="col-fixed-right text-right pr-md">
                 <div class="flex items-center justify-end gap-xs">
                   <button class="btn btn-ghost btn-icon btn-sm" @click="openEditModal(user)" title="编辑">
                     <i class="ri-edit-line"></i>
                   </button>
                   <button class="btn btn-ghost btn-icon btn-sm text-warning" @click="openResetPwdModal(user)" title="重置密码">
                     <i class="ri-key-line"></i>
                   </button>
                   <button class="btn btn-ghost btn-icon btn-sm text-danger" @click="handleDelete(user)" title="删除">
                     <i class="ri-delete-bin-line"></i>
                   </button>
                 </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

       <!-- Pagination Footer -->
       <div class="pagination-footer" v-if="users.length > 0">
         <div class="flex items-center gap-md">
           <div class="pagination-info">
             {{ paginationInfo }}
           </div>
           <div class="page-size-selector">
             <select v-model="pageSize" class="page-select" @change="handleSearch">
               <option :value="5">5条/页</option>
               <option :value="10">10条/页</option>
             </select>
             <i class="ri-arrow-down-s-line select-arrow"></i>
           </div>
         </div>
         <div class="pagination-controls">
           <button class="btn btn-sm btn-ghost" :disabled="currentPage === 1" @click="prevPage">
             <i class="ri-arrow-left-s-line"></i>
           </button>
           
           <div class="page-numbers">
              <button
                v-for="page in totalPages"
                :key="page"
                class="btn btn-sm page-btn"
                :class="{ active: currentPage === page }"
                @click="goToPage(page)"
              >
                {{ page }}
              </button>
           </div>

           <button class="btn btn-sm btn-ghost" :disabled="currentPage === totalPages" @click="nextPage">
             <i class="ri-arrow-right-s-line"></i>
           </button>
         </div>
       </div>
    </div>

    <!-- Edit/Create Modal -->
    <Teleport to="body">
      <div v-if="showModal" class="modal-overlay open" @click.self="showModal = false">
        <div class="modal open" style="width: 560px; max-height: 90vh;">
          <div class="modal-header" style="border-bottom: 1px solid var(--separator-color); padding-bottom: 16px; margin-bottom: 24px;">
            <h3 class="modal-title">{{ isEditing ? '编辑用户' : '新增用户' }}</h3>
            <button class="modal-close" @click="showModal = false"><i class="ri-close-line"></i></button>
          </div>
          <div class="modal-body grid gap-4">
            <div class="grid grid-cols-2 gap-4">
              <div class="form-group">
                  <label class="form-label">用户名 <span class="text-danger">*</span></label>
                  <input type="text" v-model="form.username" class="form-input" :disabled="isEditing" spellcheck="false" autocomplete="off" />
              </div>
               <div class="form-group">
                  <label class="form-label">姓名 <span class="text-danger">*</span></label>
                  <input type="text" v-model="form.name" class="form-input" spellcheck="false" autocomplete="off" />
              </div>
            </div>
            
            <div v-if="!isEditing" class="form-group">
               <label class="form-label">初始密码 <span class="text-danger">*</span></label>
               <input type="password" v-model="form.password" class="form-input" autocomplete="new-password" spellcheck="false" />
            </div>

            <div class="grid grid-cols-2 gap-4">
                <div class="form-group">
                   <label class="form-label">角色</label>
                   <div class="input-wrapper">
                     <select v-model="form.role" class="form-select">
                       <option value="user">普通用户</option>
                       <option value="admin">管理员</option>
                     </select>
                     <i class="ri-arrow-down-s-line select-arrow"></i>
                   </div>
               </div>
                <div class="form-group">
                   <label class="form-label">状态</label>
                   <div class="input-wrapper">
                     <select v-model="form.status" class="form-select">
                       <option :value="1">正常</option>
                       <option :value="0">禁用</option>
                     </select>
                     <i class="ri-arrow-down-s-line select-arrow"></i>
                   </div>
               </div>
            </div>

            <div class="grid grid-cols-2 gap-4">
               <div class="form-group">
                  <label class="form-label">邮箱</label>
                  <input type="email" v-model="form.email" class="form-input" spellcheck="false" autocomplete="off" />
              </div>
               <div class="form-group">
                  <label class="form-label">手机</label>
                  <input type="text" v-model="form.phone" class="form-input" spellcheck="false" autocomplete="off" />
              </div>
            </div>

             <div class="grid grid-cols-2 gap-4">
               <div class="form-group">
                  <label class="form-label">部门</label>
                  <input type="text" v-model="form.department" class="form-input" spellcheck="false" autocomplete="off" />
              </div>
               <div class="form-group">
                  <label class="form-label">职位</label>
                  <input type="text" v-model="form.position" class="form-input" spellcheck="false" autocomplete="off" />
              </div>
            </div>

          </div>
          <div class="modal-footer">
            <button class="btn btn-ghost" @click="showModal = false">取消</button>
            <button class="btn btn-primary" :disabled="modalLoading" @click="handleSubmit">保存</button>
          </div>
        </div>
      </div>
    </Teleport>
    
    <!-- Reset Password Modal -->
    <Teleport to="body">
       <div v-if="showResetPwdModal" class="modal-overlay open" @click.self="showResetPwdModal = false">
        <div class="modal open" style="width: 400px">
          <div class="modal-header" style="border-bottom: 1px solid var(--separator-color); padding-bottom: 16px; margin-bottom: 24px;">
            <h3 class="modal-title">重置密码 - {{ resetPwdForm.username }}</h3>
            <button class="modal-close" @click="showResetPwdModal = false"><i class="ri-close-line"></i></button>
          </div>
          <div class="modal-body">
               <div class="form-group">
                  <label class="form-label">新密码 <span class="text-danger">*</span></label>
                  <input type="text" v-model="resetPwdForm.password" class="form-input" placeholder="请输入新密码" spellcheck="false" autocomplete="off" />
              </div>
          </div>
          <div class="modal-footer">
            <button class="btn btn-ghost" @click="showResetPwdModal = false">取消</button>
            <button class="btn btn-primary" @click="handleResetPwd">确认重置</button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
/* Search Input Styles (Copied from ProjectsView) */
.search-input-wrapper {
  position: relative;
  display: flex;
  align-items: center;
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-md);
  padding: 6px 12px;
  width: 260px;
  transition: all 0.2s;
}

.search-input-wrapper:focus-within {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 2px rgba(var(--color-primary-rgb), 0.1);
}

.search-icon {
  font-size: 16px;
  color: var(--text-tertiary);
  margin-right: 8px;
  flex-shrink: 0;
}

.search-input {
  border: none;
  background: none;
  outline: none;
  font-size: 14px;
  color: var(--text-primary);
  width: 100%;
  padding: 0;
  height: 20px;
  line-height: 20px;
}

.search-input::placeholder {
  color: var(--text-tertiary);
}

[data-theme='dark'] .search-input-wrapper {
  background: rgba(255, 255, 255, 0.05);
  border-color: rgba(255, 255, 255, 0.1);
}

[data-theme='dark'] .search-input-wrapper:focus-within {
  border-color: var(--color-primary);
  background: rgba(255, 255, 255, 0.08);
}

/* Data Table Styles (Copied from ProjectsView) */
.data-table {
  width: 100%;
  border-collapse: collapse;
  min-width: 800px;
}

.data-table th,
.data-table td {
  padding: var(--spacing-md);
  text-align: left;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
  white-space: nowrap;
}

[data-theme='dark'] .data-table th,
[data-theme='dark'] .data-table td {
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.data-table th {
  font-weight: 500;
  color: var(--text-secondary);
  font-size: 13px;
}

/* Status Indicators */
.status-dot {
    display: inline-block;
    width: 6px;
    height: 6px;
    border-radius: 50%;
    margin-right: 6px;
}

.badge {
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 500;
    border: 1px solid transparent;
}
.badge-primary { 
  background: rgba(var(--color-primary-rgb), 0.1); 
  color: var(--color-primary); 
  border-color: rgba(var(--color-primary-rgb), 0.2);
}
.badge-secondary { 
  background: rgba(150, 150, 150, 0.1); 
  color: var(--text-secondary); 
  border-color: rgba(150, 150, 150, 0.2);
}

.text-danger { color: var(--color-danger, #ff4d4f); }
.bg-success { background-color: var(--color-success); }
.bg-danger { background-color: var(--color-danger); }

/* Fixed Columns Styles */
.col-fixed-right {
  position: sticky;
  right: 0;
  z-index: 10;
  background: var(--bg-content);
  backdrop-filter: blur(12px);
  border-left: 1px solid rgba(0, 0, 0, 0.05);
}

[data-theme='dark'] .col-fixed-right {
  border-left: none;
  background: #333335 !important;
  backdrop-filter: none;
}

[data-theme='dark'] th.col-fixed-right,
[data-theme='dark'] td.col-fixed-right {
  background: #333335 !important;
}

[data-theme='dark'] tr:hover td.col-fixed-right {
  background: #333335 !important;
}

/* Pagination Footer */
.pagination-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
  border-top: 1px solid var(--border-color);
}

.pagination-info {
  font-size: 13px;
  color: var(--text-secondary);
}

.page-size-selector {
  position: relative;
  display: flex;
  align-items: center;
}

.page-select {
  appearance: none;
  background: transparent;
  border: 1px solid transparent;
  padding: 4px 24px 4px 8px;
  border-radius: var(--radius-sm);
  font-size: 13px;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.page-select:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.page-select:focus {
  outline: none;
  border-color: var(--color-primary);
}

.select-arrow {
  position: absolute;
  right: 6px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 14px;
  color: var(--text-tertiary);
  pointer-events: none;
}

.pagination-controls {
  display: flex;
  align-items: center;
  gap: 8px;
}

[data-theme='dark'] .pagination-footer {
  border-top-color: rgba(255, 255, 255, 0.05);
}


/* Form Styles (Matched with SettingsView Notification Modal) */
.form-group {
  margin-bottom: var(--spacing-md);
}

.form-label {
  display: block;
  font-size: 13px;
  color: var(--text-secondary);
  margin-bottom: var(--spacing-sm);
  font-weight: 500;
}

.form-input,
.form-select {
  width: 100%;
  padding: 10px 14px;
  background: var(--bg-base); /* Changed to Match ProjectCreateView */
  border: 1px solid var(--border-color);
  border-radius: var(--radius-sm);
  color: var(--text-primary);
  outline: none;
  transition: border-color 0.2s;
  font-size: 14px;
}

.form-input:focus,
.form-select:focus {
  border-color: var(--color-primary);
  background: var(--bg-base); 
}

.form-select {
  appearance: none;
  /* Removed background-image */
  padding-right: 28px;
}

.input-wrapper {
  position: relative;
}

.input-wrapper .select-arrow {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
  font-size: 16px;
  color: var(--text-tertiary);
  pointer-events: none;
}

[data-theme='dark'] .form-input,
[data-theme='dark'] .form-select {
  background: rgba(0, 0, 0, 0.2); /* Darker background for inputs on elevated modal */
  border-color: rgba(255, 255, 255, 0.1);
}

[data-theme='dark'] .form-input:focus,
[data-theme='dark'] .form-select:focus {
  border-color: var(--color-primary);
  background: rgba(0, 0, 0, 0.4);
}
</style>
