// frontend/src/views/DashboardView.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { dashboardApi, type DashboardStats } from '@/api/dashboard'
import type { Payment, Project } from '@/api/project'
import IncomeChart from '@/components/dashboard/IncomeChart'
import ProjectList from '@/components/dashboard/ProjectList'
import QuickActions from '@/components/dashboard/QuickActions'
import StatCard from '@/components/dashboard/StatCard'
import UpcomingPayments, { type PaymentDisplayItem } from '@/components/dashboard/UpcomingPayments'
import { useToastStore } from '@/composables/useToast'

type Period = 'week' | 'month' | 'quarter' | 'year'

const emptyStats: DashboardStats = {
  avg_collection_days: 0,
  avg_collection_days_trend: 0,
  overdue_amount: 0,
  overdue_trend: 0,
  paid_amount: 0,
  paid_trend: 0,
  pending_amount: 0,
  pending_trend: 0,
  total_amount: 0,
  total_trend: 0,
}

const toPaymentDisplay = (payment: Payment): PaymentDisplayItem => {
  const due = new Date(payment.plan_date)
  const today = new Date()
  const days = Math.ceil((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))

  return {
    amount: payment.amount,
    client_name: payment.project?.company || '未知客户',
    days_left: Math.max(0, days),
    id: payment.id,
    project_id: payment.project_id,
    project_name: payment.project?.name || '未知项目',
    status: days < 0 ? 'danger' : days < 3 ? 'danger' : days < 7 ? 'warning' : 'success',
  }
}

export default function DashboardView() {
  const toastError = useToastStore((state) => state.error)
  const [statsData, setStatsData] = useState<DashboardStats>(emptyStats)
  const [incomeLabels, setIncomeLabels] = useState<string[]>([])
  const [incomeValues, setIncomeValues] = useState<number[]>([])
  const [recentProjects, setRecentProjects] = useState<Project[]>([])
  const [upcomingPayments, setUpcomingPayments] = useState<PaymentDisplayItem[]>([])
  const [activePeriod, setActivePeriod] = useState<Period>('month')
  const [, setLoading] = useState(true)

  const statsDisplay = useMemo(
    () => [
      {
        icon: 'ri-money-dollar-circle-line',
        iconColorClass: 'stat-card-icon--primary',
        label: '总收款金额',
        trend: `${Math.abs(statsData.total_trend).toFixed(2)}%`,
        trendPrefix: '较上月',
        trendUp: statsData.total_trend >= 0,
        value: `¥${statsData.total_amount.toLocaleString()}`,
      },
      {
        icon: 'ri-checkbox-circle-line',
        iconColorClass: 'stat-card-icon--success',
        label: '已结算金额',
        trend: `${Math.abs(statsData.paid_trend).toFixed(2)}%`,
        trendPrefix: '较上月',
        trendUp: statsData.paid_trend >= 0,
        value: `¥${statsData.paid_amount.toLocaleString()}`,
      },
      {
        icon: 'ri-time-line',
        iconColorClass: 'stat-card-icon--warning',
        label: '待结算金额',
        trend: `${Math.abs(statsData.pending_trend).toFixed(2)}%`,
        trendPrefix: '较上月',
        trendUp: statsData.pending_trend >= 0,
        value: `¥${statsData.pending_amount.toLocaleString()}`,
      },
      {
        icon: 'ri-error-warning-line',
        iconColorClass: 'stat-card-icon--danger',
        label: '逾期金额',
        trend: `${Math.abs(statsData.overdue_trend).toFixed(2)}%`,
        trendPrefix: '较上月',
        trendUp: statsData.overdue_trend >= 0,
        value: `¥${statsData.overdue_amount.toLocaleString()}`,
      },
    ],
    [statsData],
  )

  const fetchDashboardData = useCallback(
    async (period: Period) => {
      setLoading(true)
      try {
        const [statsRes, trendRes, projectRes, paymentRes] = await Promise.all([
          dashboardApi.getStats(),
          dashboardApi.getIncomeTrend(period),
          dashboardApi.getRecentProjects(),
          dashboardApi.getUpcomingPayments(),
        ])

        setStatsData(statsRes.data.data)
        setIncomeLabels(trendRes.data.data.labels)
        setIncomeValues(trendRes.data.data.actual_values)
        setRecentProjects(projectRes.data.data)
        setUpcomingPayments(paymentRes.data.data.map(toPaymentDisplay).slice(0, 3))
      } catch (error) {
        console.error('Failed to fetch dashboard data', error)
        toastError('获取仪表盘数据失败')
      } finally {
        setLoading(false)
      }
    },
    [toastError],
  )

  const handlePeriodChange = async (period: Period) => {
    setActivePeriod(period)
    try {
      const response = await dashboardApi.getIncomeTrend(period)
      setIncomeLabels(response.data.data.labels)
      setIncomeValues(response.data.data.actual_values)
    } catch (error) {
      console.error('Failed to update income trend', error)
      toastError('更新趋势图失败')
    }
  }

  useEffect(() => {
    window.setTimeout(() => fetchDashboardData(activePeriod), 0)
  }, [activePeriod, fetchDashboardData])

  return (
    <div className="dashboard-view">
      <div className="grid grid-cols-4" style={{ marginBottom: 'var(--spacing-lg)' }}>
        {statsDisplay.map((stat) => (
          <StatCard key={stat.label} {...stat} />
        ))}
      </div>

      <div className="grid dashboard-charts-row">
        <IncomeChart
          labels={incomeLabels}
          onPeriodChange={handlePeriodChange}
          period={activePeriod}
          values={incomeValues}
        />
        <QuickActions />
      </div>

      <div className="grid dashboard-projects-row">
        <ProjectList projects={recentProjects} />
        <UpcomingPayments payments={upcomingPayments} />
      </div>
    </div>
  )
}

// frontend/src/views/DashboardView.vue
<script setup lang="ts">
/**
 * @file DashboardView.vue
 * @description 应用仪表盘首页
 * 聚合展示核心业务指标、图表和快捷操作入口。
 * 负责并行拉取多个 API 数据接口，并组装成 UI 所需的数据结构。
 */
import { ref, onMounted, onActivated, computed } from 'vue'
import StatCard from '@/components/dashboard/StatCard.vue'
import IncomeChart from '@/components/dashboard/IncomeChart.vue'
import QuickActions from '@/components/dashboard/QuickActions.vue'
import ProjectList from '@/components/dashboard/ProjectList.vue'
import UpcomingPayments from '@/components/dashboard/UpcomingPayments.vue'
import { dashboardApi, type DashboardStats } from '@/api/dashboard'
import type { Project, Payment } from '@/api/project'
import { useToast } from '@/composables/useToast'

const toast = useToast()

const statsData = ref<DashboardStats>({
  total_amount: 0,
  paid_amount: 0,
  pending_amount: 0,
  overdue_amount: 0,
  total_trend: 0,
  paid_trend: 0,
  pending_trend: 0,
  overdue_trend: 0,
  avg_collection_days: 0,
  avg_collection_days_trend: 0,
})

const statsDisplay = computed(() => [
  { 
    label: '总收款金额', 
    value: `¥${statsData.value.total_amount.toLocaleString()}`, 
    icon: 'ri-money-dollar-circle-line', 
    trendPrefix: '较上月',
    trend: `${Math.abs(statsData.value.total_trend)}%`, 
    trendUp: statsData.value.total_trend >= 0, 
    iconColorClass: 'stat-card-icon--primary' 
  },
  { 
    label: '已结算金额', 
    value: `¥${statsData.value.paid_amount.toLocaleString()}`, 
    icon: 'ri-checkbox-circle-line', 
    trendPrefix: '较上月',
    trend: `${Math.abs(statsData.value.paid_trend)}%`, 
    trendUp: statsData.value.paid_trend >= 0, 
    iconColorClass: 'stat-card-icon--success' 
  },
  { 
    label: '待结算金额', 
    value: `¥${statsData.value.pending_amount.toLocaleString()}`, 
    icon: 'ri-time-line', 
    trendPrefix: '较上月',
    trend: `${Math.abs(statsData.value.pending_trend)}%`, 
    trendUp: statsData.value.pending_trend >= 0, // Pending trend up might be bad? Usually context dependent. optimized: false? Keeping simple.
    iconColorClass: 'stat-card-icon--warning' 
  },
  { 
    label: '逾期金额', 
    value: `¥${statsData.value.overdue_amount.toLocaleString()}`, 
    icon: 'ri-error-warning-line', 
    trendPrefix: '较上月',
    trend: `${Math.abs(statsData.value.overdue_trend)}%`, 
    trendUp: statsData.value.overdue_trend >= 0, // Overdue up is definitely bad. But trendUp usually just controls arrow direction.
    iconColorClass: 'stat-card-icon--danger' 
  },
])

const incomeLabels = ref<string[]>([])
const incomeValues = ref<number[]>([])

const recentProjects = ref<Project[]>([])
// Use correct type for payments
interface PaymentDisplayItem {
  id: number
  project_id: number
  project_name: string
  client_name: string
  days_left: number
  amount: number
  status: string
}
const upcomingPayments = ref<PaymentDisplayItem[]>([])

const loading = ref(true)

const activePeriod = ref<'week' | 'month' | 'quarter' | 'year'>('month')

const fetchDashboardData = async () => {
  loading.value = true
  try {
    // 并行请求所有数据，提升加载速度
    const [statsRes, trendRes, projectRes, paymentRes] = await Promise.all([
      dashboardApi.getStats(),
      dashboardApi.getIncomeTrend(activePeriod.value),
      dashboardApi.getRecentProjects(),
      dashboardApi.getUpcomingPayments(),
    ])

    if (statsRes.data.code === 0) {
      statsData.value = statsRes.data.data
    }

    if (trendRes.data.code === 0) {
      incomeLabels.value = trendRes.data.data.labels
      incomeValues.value = trendRes.data.data.actual_values
    }

    if (projectRes.data.code === 0) {
      recentProjects.value = projectRes.data.data
    }

    if (paymentRes.data.code === 0) {
      upcomingPayments.value = paymentRes.data.data.map((p: Payment) => {
        // 使用标准日期计算剩余天数
        const due = new Date(p.plan_date)
        const today = new Date()
        const diffTime = due.getTime() - today.getTime()
        const days = Math.ceil(diffTime / (1000 * 60 * 60 * 24))
        
        return {
          id: p.id,
          project_id: p.project_id,
          project_name: p.project ? p.project.name : '未知项目',
          client_name: p.project ? p.project.company : '未知客户',
          days_left: days >= 0 ? days : 0, 
          amount: p.amount,
          status: days < 0 ? 'danger' : days < 3 ? 'danger' : days < 7 ? 'warning' : 'success'
        }
      })
    }

  } catch (error) {
    console.error('Failed to fetch dashboard data', error)
    toast.error('获取仪表盘数据失败')
  } finally {
    loading.value = false
  }
}

const handlePeriodChange = async (period: 'week' | 'month' | 'quarter' | 'year') => {
  activePeriod.value = period
  try {
    const res = await dashboardApi.getIncomeTrend(period)
    if (res.data.code === 0 && res.data.data) {
      incomeLabels.value = res.data.data.labels
      incomeValues.value = res.data.data.actual_values
    }
  } catch (error) {
    console.error('Failed to update income trend', error)
  }
}

onMounted(() => {
  fetchDashboardData()
})

onActivated(() => {
  fetchDashboardData()
})
</script>

<template>
  <div class="dashboard-view">
    <!-- Stats Grid -->
    <div class="grid grid-cols-4" style="margin-bottom: var(--spacing-lg);">
      <StatCard
        v-for="stat in statsDisplay"
        :key="stat.label"
        v-bind="stat"
      />
    </div>

    <!-- Charts & Actions -->
    <div class="grid dashboard-charts-row">
      <IncomeChart 
        :labels="incomeLabels" 
        :values="incomeValues" 
        v-model="activePeriod"
        @change="handlePeriodChange"
      />
      <QuickActions />
    </div>

    <!-- Projects & Payments -->
    <div class="grid dashboard-projects-row">
      <ProjectList :projects="recentProjects" />
      <UpcomingPayments :payments="upcomingPayments" />
    </div>
  </div>
</template>

<style scoped>
.dashboard-charts-row {
  grid-template-columns: 2fr 1fr;
  align-items: stretch;
  margin-bottom: var(--spacing-lg);
}

.dashboard-projects-row {
  grid-template-columns: 2fr 1fr;
  align-items: stretch;
}

@media (max-width: 1024px) {
  .dashboard-charts-row,
  .dashboard-projects-row {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 768px) {
  .dashboard-charts-row,
  .dashboard-projects-row {
    gap: var(--spacing-md);
  }
}
</style>
